
spring:
  application:
    name: gateway-api
  profiles:
    active: prod

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.autoconfigure.data.r2dbc.R2dbcDataAutoConfiguration

  cloud:
    gateway:
      routes:
        # 1. Роутинг на сервис Авторизации (OAuth2)
        - id: oauth2-route
          # Перенаправляем на имя докер-контейнера сервиса авторизации
          uri: ${OAUTH2_SERVICE_URL:http://oauth2-container:8087}
          predicates:
            - Path=/api/v1/auth/**, /oauth2/**
          #  - Method=GET,POST
          #  - Header=X-API-VERSION, v2     # Дополнительные настройки безопасности: шлюз вернет ошибку 404 Not Found.
          # Он откажется перенаправлять запрос, пока вы принудительно не добавите в HTTP-заголовки (Headers) строчку X-API-VERSION: v1.
          #filters: # пример переделки url если нужно
          #  - RewritePath=/api/users/(?<segment>.*), /users/${segment}    # /api/users/1 → /users/1

        # 2. Роутинг на сервис Валют (Currencies)
        - id: currencies-route
          uri: ${CURRENCIES_SERVICE_URL:http://currencies-container:8081} # Порт 8081 внутри своего контейнера
          predicates:
            - Path=/api/v1/currencies/**
          #  - Method=GET,POST,PUT,DELETE  # поддерживаемые HTTP методы
          #  - Header=X-API-VERSION, v1

        # 3. Роутинг на сервис Кредитных Карт
        - id: credit-cards-route
          uri: http://credit-card-container:8081 # ИМЯ КОНТЕЙНЕРА вместо localhost!
          predicates:
            - Path=/api/v1/credit-cards/**

        # 4. Сервис Платежей (Payments) — Участник Саги
        - id: payments-route
          uri: ${PAYMENTS_SERVICE_URL:http://payments-container:8082}
          predicates:
            - Path=/api/v1/payments/**

        # 5. Сервис Мониторинга (Monitoring)
        - id: monitoring-route
          uri: ${MONITORING_SERVICE_URL:http://monitoring-container:8084}
          predicates:
            - Path=/api/v1/monitoring/**

resilience4j:
  retry:
    instances:
      userServiceRetry:
        max-attempts: 3
        wait-duration: 500ms
  circuitbreaker:
    instances:
      userServiceCB:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s

management:
  health:
    r2dbc:
      enabled: false

security:
  jwt:
    secret: ${JWT_SECRET}

server:
  port: 8088